### ISSUE TITLE
UFP Plugin - Images Get Removed

### ISSUE THREAD

**Issue by jneilliii** [OllisGit/OctoPrint-DeleteAfterPrint#11]
Hey @OllisGit, someone posted an issue on my UFP plugin repo about the images getting deleted [here](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/issues/10) with this plugin enabled.  I know the issue is on my plugin's side on the [FileRemoved](https://docs.octoprint.org/en/master/events/index.html#file-handling) event, as that triggers the deletion of the original file and then triggers the FileAdded event in it's new location. There doesn't seem to be any way to avoid this, so I was wondering if it would be easier to add some logic in this plugin to also move the other supporting files if the UFP plugin is installed? I'm going to look through your code to see if I can implement this logic and will probably submit a PR.

**Comment by OllisGit** [comment]
You need to use UFP - Plugin Version 0.1.4+
