### ISSUE TITLE
Can't find the plug in 

### ISSUE THREAD

**Issue by icancwhatusay** [OllisGit/OctoPrint-DeleteAfterPrint#12]
I'm setting up a new Pi and printer and I'm trying to find the plugin but it's not showing up in the search

https://plugins.octoprint.org/search/?q=delete

**Comment by OllisGit** [comment]
Hi @icancwhatusay ,

it's working for me. The first entry:
![image](https://user-images.githubusercontent.com/24205767/76830992-b7ce0680-6826-11ea-90dc-7f7f237fc7ad.png)

**Comment by icancwhatusay** [comment]
Bizarre...the only one coming up for me yesterday was made by someone else. anyways, thanks
