### ISSUE TITLE
Additionsl Functional Idea

### ISSUE THREAD

**Issue by Brebinator** [OllisGit/OctoPrint-DeleteAfterPrint#13]
Hi there, 

Thanks for writing this plugin. :) 

I thought perhaps based on the core outcomes of a job (Success, Failure, Stopped etc.) that perhaps some additional folders or a sendmail with an attached stub may be viable?

Just some thoughts and thanks. 
Brebs

**Comment by OllisGit** [comment]
Hi @Brebinator !
hmmm...there were other plugins for notification.
Look into the plugin-repository:

https://plugins.octoprint.org/search/?q=notification

**Comment by Brebinator** [comment]
Thx, will do.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
