### ISSUE TITLE
This plugin is incompatible with The Spaghetti Detective (TSD)

### ISSUE THREAD

**Issue by dburr** [OllisGit/OctoPrint-DeleteAfterPrint#14]
I'm running into a really weird problem that I have tracked down to an incompatibility/bad interaction between the DeleteMoveAfterPrint plugin and The Spaghetti Detective (TSD).

Symptoms are: TSD does not issue a "print finished" notification at the time the print finishes. OctoPrint always shows the print ending (status goes from "printing" to "operational") at the actual time when it is physically done printing. But that status is apparently never communicated to TSD. I only get the TSD "print completed" notification + the timelapse uploaded at the time that I start the NEXT print. In addition, the actions that I have DeleteMoveAfterPrint configured to do, never get triggered.

I've done plugin troubleshooting (disabling + enabling plugins one by one) and have narrowed this down to an interaction/incompatibility between TSD and the DeleteMoveAfterPrint plugin.

**Comment by OllisGit** [comment]
hmm...did you already raised an issue on TSD side?

Is there some error messages in the octoprint logfile? Just increase the log level to debug to see more details:
![image](https://user-images.githubusercontent.com/24205767/89067237-2d1e1c00-d36f-11ea-870b-aaff7308d67b.png)

Maybe it is a "race-condition": file deleted and then the TSD could not found the data to do something.
One option could be, that I implement a delay of e.g. 10 seconds before deleting.
