### ISSUE TITLE
FEATURE: Do not show files deleted

### ISSUE THREAD

**Issue by AJErazzor** [OllisGit/OctoPrint-DeleteAfterPrint#15]
Is it possible to add a feature to not show files deleted pop up, or they auto disappear in the UI?

**Comment by OllisGit** [comment]
Hi @AJErazzor,

it's implemented in the latest Version 1.8.0.

BR
Olli

**Comment by AJErazzor** [comment]
> Hi @AJErazzor,
> 
> it's implemented in the latest Version 1.8.0.
> 
> BR
> Olli

Hi Tested, checked hide after some time - the > X buttons are gonne till hover but the popup doesnt go away
![image](https://user-images.githubusercontent.com/5545511/91648481-9e083f00-eaa7-11ea-956b-e650d9662b53.png)

**Comment by OllisGit** [comment]
SORRY! Now it is fixed in the latest version 1.8.1

**Comment by AJErazzor** [comment]
No popups visible but now Im not certain there ever is - is there a log that can show what has and hasnt been deleted to confirm?

**Comment by AJErazzor** [comment]
I did manage to see a pop up of a file deleted and then disappear as expected.  Is it worth adding a new request to have a list view of the historically deleted jobs?  May not be necessary if using other of your fine plugins?
