### ISSUE TITLE
Feature Enhancement

### ISSUE THREAD

**Issue by oxgon** [OllisGit/OctoPrint-DeleteAfterPrint#2]
add auto deletion based on time. 
Waiting days or weeks till deletion would be great!

**Comment by OllisGit** [comment]
Looks like a good idea. I will check if it's possible to implement.
BR
Olli

**Comment by OllisGit** [comment]
@oxgon Implementation is done!

The new Release 1.1.0 is out. Please test the enhancement.
Thx, in advance
Olli

**Comment by oxgon** [comment]
wow, that was fast! I love this so far; it has saved me a lot of work, I print a lot and always hated going through my queue and spamming the delete button. Keep up the excellent work.

**Comment by OllisGit** [comment]
@oxgon After installation and reloading the page, are all old files automaticaly deleted?
Because there is issue #3.
So it is really importend to know the behaviour after first installation. I couldn't reproduced this issue.
Please so kind and give me a fast answer!

Thx, in advance
Olli

**Comment by oxgon** [comment]
@OllisGit I currently don't have any in there that are past the day mark.

**Comment by OllisGit** [comment]
thanks for your feedback.....I think about a "userfrindly"-solution for the next release. See #3
