### ISSUE TITLE
great plugin - one suggestion

### ISSUE THREAD

**Issue by empakoso** [OllisGit/OctoPrint-DeleteAfterPrint#21]
Could you make the option to leave the menu minimized (collapsed) state, as left when restarting OctoPrint?  The menu defaults to being expanded each time OctoPrint is opened.

**Comment by OllisGit** [comment]
Please use: https://plugins.octoprint.org/plugins/statefulsidebar/

**Comment by empakoso** [comment]
Thanks.  Works perfect.
