### ISSUE TITLE
enhancement: only autodelete in root folder

### ISSUE THREAD

**Issue by bdynamic** [OllisGit/OctoPrint-DeleteAfterPrint#4]
it would be great to have an option only deleting in the root of the folder hierarchy.
There are certain models which I would like to keep, but those get normally sorted into folders.
The quick "slice and send to printer" from slic3r is stored in the root folder. For those the auto delete would be perfect.

**Comment by OllisGit** [comment]
@bdynamic I released a new version of this plugin (V1.3.0). Now you can decide to delete files after print in sub-folders.
Please test and give a feedback!

Thx, 
Olli

**Comment by OllisGit** [comment]
No feedback -> closed!
