### ISSUE TITLE
[Feature request] Add the option to hide the icon in the nav bar

### ISSUE THREAD

**Issue by calania** [OllisGit/OctoPrint-DeleteAfterPrint#5]
I really like this plugin, but the thing is that I haven't touched any of its settings since I installed it. I like to have as few things as possible in my navbar and since I don't change the plugin settings I don't see the need of having the icon in the navbar. Any chance you could make a setting so that I can turn the icon off?

**Comment by OllisGit** [comment]
@calania  It's fixed in Version 1.2.0
Icon is now only shown if "DayDelete" is enabled.
Please test and give feedback.

BR
Olli
