### ISSUE TITLE
Files in subfolders don't get removed

### ISSUE THREAD

**Issue by notoriousbad** [OllisGit/OctoPrint-DeleteAfterPrint#6]
Really like the plugin, thanks for putting your time into it! I noticed that files that have been moved into subdirectories don't get automatically deleted by the plugin. Files in the root directory - no problem. Kindly refer to the sceenshot.

![image](https://user-images.githubusercontent.com/46992779/51668264-1fd9e180-1fc2-11e9-8eeb-ef231b301ebe.png)

![image](https://user-images.githubusercontent.com/46992779/51668386-63cce680-1fc2-11e9-8d99-01c9a41e5fcb.png)

**Comment by OllisGit** [comment]
@notoriousbad  I released a new version of this plugin (V1.3.0). Now you can decide to delete files after print in sub-folders.
Please test and give a feedback!

Thx,
Olli

**Comment by OllisGit** [comment]
No feedback -> closed!
