### ISSUE TITLE
Feature request: delete failed prints

### ISSUE THREAD

**Issue by hsuomal** [OllisGit/OctoPrint-DeleteAfterPrint#7]
For automated workflows where prints get pushed all over, it would be usefull to be able to delete failed or cancelled job files too. Perhaps a separate checkbox to allow this and a different time amount in case anyone needs difference could be very usefull.

**Comment by OllisGit** [comment]
@hsuomal  I released a new version with your feature request.
Please test and give me a feedback.

Thx, in advance
Olli

**Comment by OllisGit** [comment]
Closed: No feedback, so far!
