### ISSUE TITLE
Add option to move the files into a specified folder instead of deleting.

### ISSUE THREAD

**Issue by Oxmaster** [OllisGit/OctoPrint-DeleteAfterPrint#8]
I think this plugin could use an option to move files to a "trash" folder. So far I've been using the default option with octoprint to hide completed prints, but this is session specific, so if I log in with different device, this setting resets. All the rules would still be the same as the deletion option, but instead it would move the file instead of removing it. I don't know python (if I knew I would do it myself), but it should be an easy addition.

**Comment by OllisGit** [comment]
@Oxmaster  sound like a good idea.
I will check if it could be done with less effort.

**Comment by OllisGit** [comment]
@Oxmaster the feature is implemented in newest version 1.5.0. 
Btw. It was not easy!!! I need to change a lot of stuff...several UIs, logik and testing, testing, testing.

Please test it and give me a feedback.
BR
Olli

**Comment by OllisGit** [comment]
Closed: No feedback, so far!
