### ISSUE TITLE
Add feature to disable notification

### ISSUE THREAD

**Issue by SteeveGL** [OllisGit/OctoPrint-DeleteAfterPrint#9]
I didn't find a way to disable plugin notification from Octoprint. So, I guess each plugin have to manage it's own notification.

Actually to me the notification about my file has been removed annoying me. I have a screen always open to monitor my printer and I never touch this page. So I have permanently a pop-up saying my last print has been removed. This notification is useless in my case.

**Comment by OllisGit** [comment]
Hi @steevegldev ,

new feature is implemented in V1.6.0. Please test and give feedback.

BR
Olli

**Comment by SteeveGL** [comment]
Work as expected. Thanks you.
